# name: Correction

# on:
#   # 1.2
#   # push:
#   #   branche:
#       # - dev
#   # 1.3
#   # push:
#   #   branches:
#   #    - '!staging'
#   # 1.4
#   # push:
#   #   branches:
#   #     - 'feat/**'
#   # 1.5
#   # push:
#   #   branches:
#   #     - '**.ts'
#   # 1.6
#   # push:
#   #   paths:
#   #     - node-app
#   # 2.1
#   # pull_request:
#   #   types:
#   #     - opened
#   # 2.2
#   # pull_request:
#   #   types:
#   #     - closed
#   # 3.1
#   # schedule:
#   #   - cron: '*/5 * * * *'
#   # 3.2
#   # schedule:
#   #   - cron: '0 0/3 * * *'
#   #   - cron: '30 1/3 * * *'
#   # 3.3
#   # schedule:
#   #   -cron: '0 3 * * TUE'
#   workflow_dispatch:
# jobs: 
#   build:
#     runs-on: ubuntu-latest
#     steps: 
#       - uses: actions/checkout@v3
#   deploy:
#     if: github.event_name != 'pull_request'
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

# MAtrix
# name: Matrix 1

# on:
#   # Manual
#   workflow_dispatch:

# jobs:
#   build-test:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         version: [12, 14, 12]

#     defaults:
#       run:
#         working-directory: node-app

#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.version }}

#       - name: Install dependencies
#         run: |
#           npm ci
# MAtrix 2 
# name: Matrix 2

# on:
#   workflow_dispatch:

# jobs:
#   build-test:
#     strategy:
#       matrix:
#         version: [12, 14, 16]
#         os: [ubuntu-latest, windows-latest]

#     # Without this line, the failing matrix job will prevent other from starting
#     continue-on-error: true
#     runs-on: ${{ matrix.os }}

#     defaults:
#       run:
#         working-directory: node-app

#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.version }}

#       - name: Install dependencies
#         run: |
#           npm ci
# Self Hosted
name: Self hosted runner

on:
  push:

jobs:
  build-test:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: node-app

    steps:
      - uses: actions/checkout@v3
      # No need to install nodejs as it is already installed locally
      - name: Install dependencies
        run: |
          npm ci
      - name: Test
        run: |
          npm test
      - name: Start the app
        run: |
          npm start