name: Correction

on:
  # 1.2
  # push:
  #   branche:
      # - dev
  # 1.3
  # push:
  #   branches:
  #    - '!staging'
  push:
    branches:
      - 'feat/**'
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3