name: Correction

on:
  # 1.2
  # push:
  #   branche:
      # - dev
  # 1.3
  # push:
  #   branches:
  #    - '!staging'
  # 1.4
  # push:
  #   branches:
  #     - 'feat/**'
  # 1.5
  # push:
  #   branches:
  #     - '**.ts'
  push:
    paths:
      - node-app
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3