name: Correction

on:
  # 1.2
  # push:
  #   branche:
      # - dev
  # 1.3
  # push:
  #   branches:
  #    - '!staging'
  # 1.4
  # push:
  #   branches:
  #     - 'feat/**'
  # 1.5
  # push:
  #   branches:
  #     - '**.ts'
  # 1.6
  # push:
  #   paths:
  #     - node-app
  # 2.1
  # pull_request:
  #   types:
  #     -opened
  pull_request:
    types:
      -closed
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3